runtime: nodejs20
instance_class: F1
service: web-homework

env_variables:
  VITE_API_URL: "https://api-homework-dot-dev-chepita.uc.r.appspot.com/api/v1"
  VITE_PUBLIC_KEY: "abc123xyz"

automatic_scaling:
  max_instances: 1

handlers:
  # ⚙️ Archivos JS, CSS, imágenes, fuentes, etc.
  - url: /assets/(.*)
    static_files: dist/assets/\1
    upload: dist/assets/(.*)

  # 📄 Sirve index.html como HTML (¡esto es clave!)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    mime_type: text/html