runtime: nodejs20
instance_class: F1
service: web-homework
env_variables:
  VITE_API_URL: "https://api-homework-dot-dev-chepita.uc.r.appspot.com/api/v1"
  VITE_PUBLIC_KEY: "abc123xyz"
automatic_scaling:
  max_instances: 1
handlers:
  - url: /(.+)
    static_files: dist/index.html
    upload: dist/index.html

  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)
    require_matching_file: false